FROM phusion/baseimage:latest
MAINTAINER Berend Weel <b.weel@esciencecenter.nl>

# Keep ssh running
RUN rm -f /etc/service/sshd/down
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh

RUN apt-get update && apt-get install -y nodejs nodejs-legacy npm git libsass-dev
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs

RUN /usr/sbin/useradd -p $(openssl passwd simcity) -d /home/simcity -m --shell /bin/bash simcity

RUN npm i -g n
RUN n latest
RUN mv /usr/bin/npm /usr/bin/npm2 && ln -s /usr/local/bin/npm /usr/bin/npm

RUN echo "export PATH=/home/simcity/npm/bin:$PATH" >> /home/simcity/.bashrc && echo "export PREFIX=/home/simcity/npm" >> /home/simcity/.bashrc && echo "export N_PREFIX=/home/simcity/npm" >> /home/simcity/.bashrc

USER simcity

ENV PATH=/home/simcity/npm/bin:$PATH
ENV PREFIX=/home/simcity/npm
ENV export N_PREFIX=/home/simcity/npm

RUN echo "$PREFIX - $N_PREFIX - $PATH"

RUN npm i -g n
RUN n latest
RUN npm i -g npm
RUN npm i -g typescript bower nodemon http-server gulp node-gyp js-beautify typings randomatic arr-flatten throat readable-stream write-file-atomic



#RUN mkdir /home/simcity/simcity
#WORKDIR /home/simcity/simcity

#WORKDIR /home/simcity/

#RUN echo "REload... - 1"

#RUN npm i -g n
#RUN npm i -g npm
#RUN n latest
#RUN npm i -g typescript bower nodemon http-server gulp node-gyp js-beautify typings
#RUN npm i -g randomatic arr-flatten throat readable-stream write-file-atomic

RUN echo "Force reload..."
COPY start-devel.sh /home/simcity/start.sh

USER root
#RUN chmod +x /home/simcity/start.sh
COPY run /etc/service/simcity/
#COPY projects /home/simcity/simcity/sim-city-cs/public/data/projects

EXPOSE 3003

#USER simcity
CMD ["/sbin/my_init"]
